### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by skeebuzz** [farmisen/react-native-file-uploader#11]
Using RN 0.43.2. 

build.gradle:
- compileSdkVersion 25
- targetSdkVersion 22

Works no problem on iOS, and compiles fine but during runtime on Android I'm getting: [undefined is not an object(evaluating '_reactNative.NativeModules.FileUploader.upload')]，Cannot read property 'upload' of undefined2. 

This guy ran into it as well: http://stackoverflow.com/questions/39243849/how-to-upload-photo-in-react-native-android

**Comment by SvetlanaPrudnikova** [comment]
Try to add in your android/app/src/main/java/.../MainApplication.java following lines: 
import com.farmisen.react_native_file_uploader.RCTFileUploaderPackage;

and in your method override

`    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RCTFileUploaderPackage() <-----add this line
      );
    }
  };`

**Comment by skeebuzz** [comment]
Yup, that was it. Not sure why the linking failed in MainApplication. Checked settings.gradle & build.gradle and those were fine. But the same thing happened with another module (react-native-permissions), which this tip helped me to diagnose. 

Cheers
